#!/usr/bin/env nimexec
#PBS -N NimrodDemo
#PBS -A UQ-RCC
#PBS -l walltime=168:00:00
#PBS -l select=2:ncpus=24:ompthreads=2:mem=24GB

#NIM shebang /bin/bash
#NIM parameter i integer range from 0.005 to 0.2 step 0.005
#NIM parameter s values in Hake, Sablefish


# Pollock #Hake Sablefish Herring

module load anaconda
source activate /groups/MolFishLab/seqDataPy3.6

Rscript Initialize_Pops.R $NIMROD_VAR_s
Rscript SingleShotModel4Nimrod.R $NIMROD_VAR_i 50 $NIMROD_VAR_s

